version: "3.7"
services:
  app:
    image: blog
    depends_on:
    - mysql
    ports:
    - 80:5000
    networks:
    - blog
    working_dir: /app
    volumes:
    - ./:/app
    environment:
      FLASK_DEBUG: 1
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - '3306:3306'
    networks:
    - blog
    environment:
      MYSQL_ROOT_PASSWORD: crosby87
      MYSQL_DATABASE: blog

volumes:
  mysql_data:

networks:
  blog: {}
